### ISSUE TITLE
Clarification of X11 instructions

### ISSUE THREAD

**Issue by wdross** [Team2168/2168_Vision_Example#1]
Awesome repository!
We (3618 - Petoskey Paladins) have been able to follow all the instructions and can run the vision example on the roboRio.

Our stumbling block is X11 forwarding, as described on [http://controls.team2168.org/](http://controls.team2168.org/) 
We've added the line
`src/gz angstrom-base http://feeds.angstrom-distribution.org/feeds/next/ipk/eglibc/armv7a/base/`
to the new `/etc/opkg/angstrom-base-feed.conf` file, ran `opkg update`, but when we invoked `opkg install xauth` we're told "Unknown package 'xauth'."

`opkg search` yields no 'auth' packages of any kind.

Any pointers on what might have been overlooked?

We're just trying to get a view into the processing to see the intermediate processing.

Thanks

**Comment by NotInControl** [comment]
can you confirm that you have a successful internet connection on the roborio?

what is the output of 'wget www.google.com'

xauth is in the angstrom repo so your problem most likely is that opkg update didnt work correctly...

**Comment by wdross** [comment]
Sorry about that.
I did have internet connectivity, but when double-checking the output of `opkg update` I couldn't see `feeds.angstrom-distribution.org` on the list.  Further investigation showed I placed the .conf file in the wrong folder.
I corrected my error and it works as expected.
Thanks, and sorry again!

**Comment by NotInControl** [comment]
awesome.. good luck

**Comment by ghost** [comment]
I follow the instructions but on doing a opkg update after adding src/gz angstrom-base http://feeds.angstrom-distribution.org/feeds/next/ipk/eglibc/armv7a/base/
I get a Failed to download http://feeds.angstrom-distribution.org/feeds/next/ipk/eglibc/armv7a/base/Packages.gz
wget returned 1
I have internet access, can ping google etc.
Has the string changed??
Thanks

**Comment by ghost** [comment]
Actual response to opkg update....
Collected errors:
 * opkg_download_backend: Failed to download http://feeds.angstrom-distribution.org/feeds/next/ipk/eglibc/armv7a/base/Packages.gz, wget returned 1.
admin@roboRIO-4069-FRC:~#

**Comment by NotInControl** [comment]
looks like the feed link did change. Are you attempting to do this on a RoboRio? Try this feed link instead, if it works, I will update the feed link on our site
http://feeds.angstrom-distribution.org/feeds/v2016.06/ipk/glibc/armv7ab-vfp/base/

**Comment by ghost** [comment]
Hmmm, I used a earlier one
http://feeds.angstrom-distribution.org/feeds/v2012.05/ipk/eglibc/armv7a/base/
and the program compiles and I see video on my mingx server....its 2012, not 2016, not sure if 2016 is better?

**Comment by ghost** [comment]
what is the diff between arm7a and arm7ab-vfp?

**Comment by NotInControl** [comment]
ARM has many different architectures, which uses a lot of co-processors or extensions to its instruction set to handle floating point numbers. Such as Neon processors, hard float (HF), and vector floating point (VFP) instructions, etc. 

They extend the arm architecture to add additional handling for floating point numbers, and while some are, some are not compatible between each other. 

So essentially the difference is exactly how the binary was complied and which arm processors it can support.
